name: "\U0001F41B Bug Report"
description: Report a bug encountered while using napari-plugin-template
labels:
  - "bug"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! 🙏🏼

        Please fill out the sections below to help us reproduce the problem.

  - type: textarea
    id: bug-report
    attributes:
      label: "\U0001F41B Bug Report"
      description: "Please provide a clear and concise description of the bug."
      placeholder: "What went wrong? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "\U0001F4A1 Steps to Reproduce"
      description: "Please provide a minimal code snippet or list of steps to reproduce the bug."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "\U0001F4A1 Expected Behavior"
      description: "Please provide a clear and concise description of what you expected to happen."
      placeholder: "What did you expect to happen?"

  - type: textarea
    id: additional-context
    attributes:
        label: "\U0001F4A1 Additional Context"
        description: "Please provide any additional information or context regarding the problem here."
        placeholder: "Add any other context about the problem here."
