# This workflow is triggered when a commit is tagged with "v*"
# and when the "Test" workflow completes successfully.
# The package is built and uploaded to PyPI using OIDC token authentication.
# For more information see: https://docs.pypi.org/trusted-publishers/

name: Create Release

on:
  push:
    tags: ["v*"] # Trigger on tags matching v*, e.g., v1.0, v20.15.10
  pull_request:
    paths: [.github/workflows/make_release.yml]

jobs:
  test:
    uses: ./.github/workflows/reusable_run_tox_test.yml
    with:
      coverage: true

  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build .

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
