name: Test plugin template

on:
  schedule:
  - cron: "0 0 * * TUE" # every week on Tuesday at midnight
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - platform: windows-latest
            python-version: "3.12"
          - platform: macos-latest
            python-version: "3.12"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true

      - name: Setup headless screen
        uses: pyvista/setup-headless-display-action@c103a2ff45650d38cb71684b5dc6cdfeb9442c79 # v5.1.0
        with:
          qt: true
          wm: herbstluftwm

      - name: Test
        run: |
          # Run tox in an ephemeral uv environment, using uv for tox env management
          uvx --from "tox>=4.31" --with "tox-uv>=1" --with "tox-gh-actions" tox
